### ISSUE TITLE
Changed: Added more checks to avoid TIMER being set on objects which shouldn't tick/have a timer.

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source-X#1027]
This change should have been further elaborated. Currently, .xtimer 1 or .set timer 1 commands do not work at all in the game. Also, all live servers need to update the timer lines in the script folders.

for example;
```
serv.newitem i_gold
new.bounce
new.timer 5

```
file commands

```
serv.newitem i_gold
new.timer 5
new.bounce

```

moreover

```
serv.newitem i_gold,5,<src>,1
new.timer = 5
```

I couldn't quite understand how it reacted to a command line like this.
It needs to update the timer set to the beginning. No explanation has been given regarding this. I think this is critical.

**Comment by Jhobean** [comment]
Good report thx!

**Comment by cbnolok** [comment]
Try the last commit

**Comment by cbnolok** [comment]
Is this still an issue?

**Comment by xwerswoodx** [comment]
The problem seems like script-side here, because you can't have timer on items that is bounced in your backpack. You have to have t_eq_script or any other equipable type to use timer. Currently we have no issue about setting any timer. But if you still feel there is an issue please open the issue back.
