### ISSUE TITLE
Feature Request: @PartyAdd

### ISSUE THREAD

**Issue by DavideRei** [Sphereserver/Source-X#1054]
Could be useful a trigger that fires when a member is added to a party.
For example to add some effect on party members, like an aura, always active on party members.

**Comment by DavideRei** [comment]
thank you, it works but i think i found a bug.
If you invite 2 player to your party, with the context menu, before the party exists, and the second player accept the invite, the first invite is canceled but the player can still accept and he join a phantom party.

![image](https://github.com/Sphereserver/Source-X/assets/118212274/0d64cdd5-f917-4a59-b3d7-38703bb373af)

Another request: is it possible to invite player with the context menu even if the party already exists? right now you can invite with the context menu only the first member, but it would be convenient to invite other members with the context menu.

**Comment by xwerswoodx** [comment]
The problem is, this party context menu totally client-side. What I mean is we can't change it's design, because it's not designed in Server. The buttons automatically removed from the context when you join the party, for the invites, you can join parties after 1st player joined so it's expected behaviour but probably client doesn't parse that correctly and context updated wrongly, I can check the send packets to see if we have anything wrong from server-side about sending information for joined players, but probably it's typical client-side bugs which UO owners Osi/Bloodblabla never care to fix.

**Comment by DavideRei** [comment]
The problem is that the player who accepts the invitation last, doesn't join the party where he was invited.
The party system for that player become broken. As you can see in the screenshot, the "leave the party" button is visible (as if he were in a group) with no party members. .xshow party or .xshow isinparty return 0 and the player can't accepts further invitations. He can only logout to fix the problem.

About the context menu, isn't Sphere telling the client what entries to show in the menu? The context menu is customizable by scripts

**Comment by xwerswoodx** [comment]
I see, but I am testing on latest client and sphere, I have no issue about it, it probably client-side issue, or I don't know but seems like you only can invite 1 player to party same time, when you invite second person, it cancels automatically, and when I accept it says no invite for me. Even I joined party for 3 people still can see them in party without any issue. Probably the client you use doesn't parse it correctly,
