### ISSUE TITLE
Faction defs used as Slayer on weapon | Other defs section not working in IF statements

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1078]
So im trying to use those faction defs on the weapon -> for example SLAYER=faction_flame.
If i do this and wants to show tooltip ON=@ClientToolTip based on slayer, for all defs it works fine, except the last section.
> // Others
> faction_bovine              0100000000
> faction_flame               0200000000
> faction_ice                 0400000000
> faction_wolf                0800000000

If i test it with custom function using STRMATCH and not IF, the statement is true, but only in custom function, in trigger ON=@ClientToolTip it just doesnt either way, the statement is never true.
I have no idea what could cause this, maybe too long def number?

This is never true, even tho the slayer==<def.faction_flame>
```
IF (<SLAYER>&<def.faction_flame>)
ADDCLILOC 1072511
ENDIF
```

This somehow is true, but only inside the function, if i use this statement in trigger, not true.

```
[function ttt]
IF (strmatch(*<slayer>*,<slayer>&<def.faction_flame>))
serv.log yo <slayer>
endif
```

**Comment by AtillaG1** [comment]
![image](https://github.com/Sphereserver/Source-X/assets/25097484/4f132c8f-b70c-4df6-855c-dea115f5f8bd)

**Comment by cbnolok** [comment]
Possible solution, from a discord discussion:
nolok
 — 
15/07/2023 20:08
split the faction prop in two?
Gladie
 — 
15/07/2023 20:09
what do you mean?
nolok
 — 
15/07/2023 20:10
a better idea even
we have npcgroups and factions
some factions are exclusive to an npcgroup
still, every faction is in a big bitmask, thus we have enormous numbers
eg:

[DEFNAME npc_factions]
// Fey group (opposed to Abyss Group)
faction_fey                 01            // Super Slayer

// Elemental Group (opposed to Abyss Group)
faction_elemental           02          // Super Slayer
faction_air_elemental        04
faction_blood_elemental     08
faction_earth_elemental     010
faction_fire_elemental      020
faction_poison_elemental    040
faction_snow_elemental      080
faction_water_elemental     0100

// Abyss group (opposed to Elemental and Fey Groups)
faction_demon               0200        // Super Slayer
faction_gargoyle            0400        // Super Slayer

we could instead start from 1 when beginning a new group
eg:

[DEFNAME npc_factions]
// Fey group (opposed to Abyss Group)
faction_fey                 01            // Super Slayer

// Elemental Group (opposed to Abyss Group)
faction_elemental           01          // Super Slayer
faction_air_elemental       02
faction_blood_elemental     04
faction_earth_elemental     08

// Abyss group (opposed to Elemental and Fey Groups)
faction_demon               01        // Super Slayer
faction_gargoyle            02        // Super Slayer

that means that we have to change the code to check for both group and faction, but that will solve our problem with no additional memory footprint
or core complexities
Gladie
 — 
15/07/2023 20:16
but then would be 01 usefull twice?
because the faction system in core is done that if you have only the faction_elemental, you deal double damage to all the elementals of this group, but if you have only faction_air_elemental, you only deal tripple dmg to air elemental
maybe i dont get fully what you mean
nolok
 — 
15/07/2023 21:02
Yes
More than twice
Then we would need to split that into faction_group and faction_species/subgroup/something in the source
I have no better ideas honestly
And if the faction species is 0 but not the group, you will deal more damage to every monster in the group
The other thing that might be worth adding in the case of a rework is to enable to slay a specific defname
Maybe with another property like faction_extended, if 1 you check for additional tags containing defnames
That's an idea, maybe not the best one

**Comment by xwerswoodx** [comment]
The problem is not a range of values if I understand the issue correctly. Because 2^62 == 4,611,686,018,427,387,904 so that mean you can set values until 0x4000000000000000

The problem is EVAL not works perfectly for llong values, even faction_wolf not working correctly

`[FUNCTION t]
FACTION faction_wolf
SERV.LOG <FACTION>
IF (<FACTION>&<def.faction_wolf>)
  SERV.LOG X
ELSE
  SERV.LOG NO-X
ENDIF
IF (<FACTION>&faction_wolf)
  SERV.LOG Y
ELSE
  SERV.LOG NO-Y
ENDIF
IF <EVAL <FACTION>&0800000000>
  SERV.LOG Z
ELSE
  SERV.LOG NO-Z
ENDIF`

Returns;

`Resync complete!
19:09:(defs_faction.scp,78)0800000000
19:09:(defs_faction.scp,82)NO-X
19:09:(defs_faction.scp,87)NO-Y
19:09:(defs_faction.scp,92)NO-Z
19:09:1:'xwerswoodx' commands 't'=1`

Even faction_bird works well;

`[FUNCTION t]
FACTION faction_bird
SERV.LOG <FACTION>
IF (<FACTION>&<def.faction_bird>)
  SERV.LOG X
ELSE
  SERV.LOG NO-X
ENDIF
IF (<FACTION>&faction_bird)
  SERV.LOG Y
ELSE
  SERV.LOG NO-Y
ENDIF
IF <EVAL <FACTION>&080000000>
  SERV.LOG Z
ELSE
  SERV.LOG NO-Z
ENDIF`

Returns

`Resync complete!
19:12:(defs_faction.scp,78)080000000
19:12:(defs_faction.scp,80)X
19:12:(defs_faction.scp,85)Y
19:12:(defs_faction.scp,90)Z
19:12:1:'xwerswoodx' commands 't'=1`

080000000 equals to 2,147,483,648 which is 32bit integer max value not llong.

We probably need to change the evaluation system from int to llong to update that for 64-bit integers.

**Comment by xwerswoodx** [comment]
Okay I found out the issue, it's same as I wrote before, because _Evaluate_Conditional_EvalSingle returns as `fVal = bool(Exp_GetVal(ptcSubexpr));` while Exp_GetVal is 32bit integer it causes this issue. Changing it Exp_GetLLVal solve the problem.

**Comment by Jhobean** [comment]
But there no eval on the problematic if.  You mean server us eval on internal?

**Comment by xwerswoodx** [comment]
Yes, I meant the IF statements evaluate function like _Evaluate_Conditional_EvalSingle and QConditional for <QVAL> function not the EVAL function itself. EVAL, FVAL, HVAL etc already set 64-bit in CScriptObj.cpp but IF and QVAL have forgotten in 32-bit int. I changed both of them to 64-bit, I am testing right now but honestly it should work fine.

**Comment by Jhobean** [comment]
Now with the new action on github, .exe will be create when you create a PR. Everyone can test it easy.

**Comment by xwerswoodx** [comment]
I pushed but haven't seen how to download any pushed version honestly :))

**Comment by AtillaG1** [comment]
works, thanks.
