### ISSUE TITLE
Faction cant be read from chardef

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#1083]
Faction on npcs cant be read from chardef. Im setting the faction in on@create.

![image](https://github.com/Sphereserver/Source-X/assets/25097484/609c3474-91c1-4d95-9d8c-d56e0e9c17f3)

with .xshow faction
![image](https://github.com/Sphereserver/Source-X/assets/25097484/112c8605-3774-444b-ad99-d65c2890589b)

**Comment by DavideRei** [comment]
You can't read properties declared under @create with serv.chardef

I think that faction should work in chardef or the sphere x chardef scripts are wrong

**Comment by xwerswoodx** [comment]
Honestly as DavideRei said you can't get variables set after char created by using chardef or itemdef etc. Because the values is not saved on anywhere as they defined after you created the npc.

The only way to get these variables ia spawning invisible new npc and get the variable and remove it. Or you can place one hidden in your star chamber and you can put it's uid to your scripts for checks. Or you can search map with forchars to get one npc with same id to take info from him.

This is not a bug at all, serv.chardef is for the properties that defined inside [chardef c_...] section. Any property defined under triggers cannot be reach with it.
