### ISSUE TITLE
[Feature Request] NPCs can drink potion.

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source-X#1147]
In the past, NPCs could drink potion, but this is not the case nowadays. If you want to be added;

old;

```
		if ( pCharSrc->IsPriv(PRIV_GM) )
			return ItemBounce(pItem);

		if ( !CanCarry(pItem) )
		{
			if ( NPC_CanSpeak() )
				Speak(g_Cfg.GetDefaultMsg(DEFMSG_NPC_PET_WEAK));
			return false;
		}

		// Place item on backpack
```

new;
```
		if ( !CanCarry(pItem) )
		{
			if ( NPC_CanSpeak() )
				Speak(g_Cfg.GetDefaultMsg(DEFMSG_NPC_PET_WEAK));
			return false;
		}

		if (pItem->IsType(IT_POTION))
		{
			if (Use_Item(pItem))
			{
				return true;
			}
			else
			{
				return false;
			}
		}

		if (pCharSrc->IsPriv(PRIV_GM))
			return ItemBounce(pItem);

		// Place item on backpack
```

_The codes here are purely examples. Although many have been tested, some may need to be rewritten._

**Comment by cbnolok** [comment]
So, right now, if you drop a potion on a NPC, it isn't used but put in its backpack?

**Comment by canerksk** [comment]
> So, right now, if you drop a potion on a NPC, it isn't used but put in its backpack?

If an authorized character leaves a potion on the entity, it falls into its bag; if the character who left the potion on the entity is a player, the entity rejects it.

**Comment by xwerswoodx** [comment]
Maybe drinking potion can be good for human characters, but it can be silly if all npcs can drink it. Like why horse drink potion because you throw it on? I am not sure if there is a check under Use_Item for humans. Honestly I am totally find it wrong to add ability to drink potion for non-human creatures.

**Comment by canerksk** [comment]
> Maybe drinking potion can be good for human characters, but it can be silly if all npcs can drink it. Like why horse drink potion because you throw it on? I am not sure if there is a check under Use_Item for humans. Honestly I am totally against to the idea of adding ability to drink potion for non-human creatures. 

It seemed ridiculous to me that we chose not to add things that the community has been used to for many years and that have existed for a long time, as an option, instead of things that we personally consider ridiculous.

**Comment by xwerswoodx** [comment]
Honestly I am not a decision maker here :) I am just telling my idea about it, yes I agree it should be there for human characters, but thinking about horse still seems wrong for me. It can be added as a flag in sphere ini to allow non-human creatures drink potions on drop.

**Comment by cbnolok** [comment]
The potions can be drank only if the char giving those to them is a owner or a friend, right?

**Comment by Tolokio** [comment]
I think there are tools to let devs choose.  Not tested Example:

```
[Event e_I_Drink_given_potions]
on=@itemdropon_char
if (<act.type>==t_potion && !<serv.spell.<more1>.flags>& SPELLFLAG_HARM)
  If <f_is_my_pet <argo>>
      argo.use <act>     
      return 1
  endif
endif
```

Is hard for me to find where the fix is done. 90 commits most of them not well named (but nice work with all thoose fixes) I prefer fixes than no fixes.  Found by github browser

![image](https://github.com/user-attachments/assets/b4b9f449-c973-4d11-8f1d-7ab840e281fb)

No check for anything but sphere.ini settings. This fix make me wonder:

Should poison be drinked as well?
What happen with explosions?
Can u give poisons and explosions to npcs so they killed themselves?
Why someone removed this feature? 
Should be better to let it be customizable by trigger?

**Comment by Tolokio** [comment]
> > Maybe drinking potion can be good for human characters, but it can be silly if all npcs can drink it. Like why horse drink potion because you throw it on? I am not sure if there is a check under Use_Item for humans. Honestly I am totally against to the idea of adding ability to drink potion for non-human creatures.
> 
> It seemed ridiculous to me that we chose not to add things that the community has been used to for many years and that have existed for a long time, as an option, instead of things that we personally consider ridiculous.

"I think someone removed that feature because right now there is a trigger to customize it very easily, it requires many checks for various cases, and it can't please everyone. I don't want to talk about what I find "ridiculous", but it is related to how decisions are made.. No offense. Just pointing out a fact."
