### ISSUE TITLE
Console serv.log pointing to wrong lines in scripts?

### ISSUE THREAD

**Issue by GladieUO** [Sphereserver/Source-X#1269]
I just find out it is hard to keep track of serv.logs in scripts, since the console is pointing out wrong line numbers.
Can this issue be on my side only?

**Comment by Soulless-1** [comment]
i dont have this issue, could not duplicate it either. do you have an example?

**Comment by AtillaG1** [comment]
I might have to inspect more, because sometimes its OK, othertimes it says undefined behaviour on line 535, but on that line there is nothing to be undefined or there is a blank space.

**Comment by cbnolok** [comment]
Is this still happening with the last dev build? I fixed something that might be related.

**Comment by AtillaG1** [comment]
Line 45 cant resolve, but on line 45 is something from previous trigger --->can this be because of on the beggining of the file, first 5 lines are comments etc...? this way the lines are offset by that? 
![image](https://github.com/user-attachments/assets/f6ec447d-24eb-4e8a-bc70-82a010305b38)
![image](https://github.com/user-attachments/assets/dbd94604-9ea0-43d5-8f0c-036cd12f975a)

**Comment by cbnolok** [comment]
Should be fixed by last dev commit

**Comment by GladieUO** [comment]
Indeed is.
