### ISSUE TITLE
IncreaseHitChance & IncreaseDefChance -> Negative values

### ISSUE THREAD

**Issue by AtillaG1** [Sphereserver/Source-X#396]
So i find out that everytime you equip item that has these bonuses, after unequip it will decrease the bonus value twice (x2).
CombatFlags=00001|00002|00020|00040|040000|00008
Latest X
X script pack
![image](https://user-images.githubusercontent.com/25097484/78278478-6310d800-7516-11ea-8f51-474b72ed3e68.png)

**Comment by xwerswoodx** [comment]
I checked it now and it seems like everything is fine with latest release, could you sen your script?

**Comment by AtillaG1** [comment]
Still happening to me with latest. Using X vanilla sphere pack.
```
[ITEMDEF i_arcane_shield]
ID=i_shield_kite_wood
NAME=Arcane Shield
SpellChanneling=1
NightSight=1
IncreaseDefChance=15
FasterCasting=1
RESENERGY=1
Rarity=11
TEVENTS=ei_equipitem
TEVENTS=ei_artifact
CATEGORY=Artifacts
SUBSECTION=Doom (Gauntlet)
DESCRIPTION=Arcane Shield
ON=@Create
   COLOR=0556
   ATTR=attr_magic|attr_identified
   HITPOINTS=255
```

**Comment by AtillaG1** [comment]
https://i.gyazo.com/8547306754342a15034b868997feead8.gif

**Comment by xwerswoodx** [comment]
Yeah I tested it, seems like when you use it under ItemDef it cause that bug.

**Comment by xwerswoodx** [comment]
Seems like it's fixed after the latest update, could you check it?

**Comment by AtillaG1** [comment]
Still doubled here :(

**Comment by xwerswoodx** [comment]
The problem is, I started to work on that, I created arcane shield, it starts go negative after I unequip item, but I tired and sleep, later at the next day I want to work on it and it's working fine as it should be, so when the issue fixed itself, I don't really know how to fix it. But there is something wrong about that.

**Comment by xwerswoodx** [comment]
It's still working fine for me from that day, I haven't remembered I did anything about it but maybe someone made a change on it? Or maybe I fixed it while fixing other things. I am not sure but seems like it's working fine for me, can you check if you still has issue? Because it's really strange.

**Comment by xwerswoodx** [comment]
Hahahah pff, Okay I found out the reason. The reason is script side, because you have ei_equipitem event, and this event in default has - itemdefchance, but after we added automatic decrease in sphere, this causes double drops, you need to comment 

```IF (<IncreaseDefChance>)
	SRC.IncreaseDefChance -= <IncreaseDefChance>
	IF (<SRC.IncreaseDefChance>==0)
		SRC.SYSMESSAGELOC color_text,1062321//"Your defense chance has returned to normal."
	ENDIF
ENDIF```
lines under @UnEquip

**Comment by xwerswoodx** [comment]
Hahahah pff, Okay I found out the reason. The reason is script side, because you have ei_equipitem event, and this event in default has - itemdefchance, but after we added automatic decrease in sphere, this causes double drops, you need to comment 

```
IF (<IncreaseDefChance>)
	SRC.IncreaseDefChance -= <IncreaseDefChance>
	IF (<SRC.IncreaseDefChance>==0)
		SRC.SYSMESSAGELOC color_text,1062321//"Your defense chance has returned to normal."
	ENDIF
ENDIF
```
lines under @UnEquip And other increasehitchance blabla etc. Because they are removed under On=@Equip but doesn't removed under @UnEquip so it causes decreased twice.
