### ISSUE TITLE
@NPCRestock - Color of item not correct SET.

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#397]
Hello, 
When call @NPCRestock for add item on NPC body lilke:
`ON=@NPCRestock
    ITEM=i_shirt_plain
    COLOR=colors_all
`
Happen this problem:
- Correct add i_shirt_plain on NPC body.
- Wrong set color, Color is set on NPC Body not on ITEM.

Thx.
Alessandro

**Comment by GitMadKing** [comment]
item that npc wear is under @create and not @npcrestock
what do really need it for under @npcrestock
?

**Comment by alexdan2** [comment]
Hello, i use for backwards compatibility, but i can move all @create trigger.
i try code but happen this:

https://ibb.co/F69GB1c

**Comment by cbnolok** [comment]
Npcrestock has its sense as a trigger for that stuff, btw can you copy the script on pastebin? I suspect, as GitMadKing said, that there's a newline error

**Comment by alexdan2** [comment]
Hello i check for new line and make new clear npc whitout events ecc and happen same issue.
Here pastebin of script: https://pastebin.com/SmtnSgWT
Here a ingame video: https://www.youtube.com/watch?v=cyHfomQodAc&feature=youtu.be

I also see when npc spawn color is OK, after 0.5/1 sec he take color or weapon.
other information i can share is take color of last item in resotck, npc take 33 color.
ES:
```
	ITEM=i_dagger
	COLOR=2
	ITEM=i_apron_half
	COLOR=33
```

Thx

**Comment by GitMadKing** [comment]
on notepad++ activate "reversed P"  
an post screenshoot. (you can simply paste the screen and it.will host kn github)

**Comment by alexdan2** [comment]
This is my test script:
![image](https://user-images.githubusercontent.com/6176986/78339575-fa1c7500-7594-11ea-9126-5bdc936e1390.png)

**Comment by GitMadKing** [comment]
is the result here
![image](https://user-images.githubusercontent.com/16067766/78339858-731bcc80-7595-11ea-831f-3385a7362cc0.png)

maybe a duplicate char?

try ths:
```
[CHARDEF C_HWB]
NAME=#NAMES_HUMANMALE
ID=C_MAN
DESIRES=i_gold,e_notoriety,t_log,t_ingot
AVERSIONS=t_TRAP
ON=@Create
    TITLE=l'Armaiolo
    NPC=brain_vendor
    COLOR=55
    STR={86 100}
    DEX={86 100}
    INT={81 95}
    ARMSLORE=100.0
    BLACKSMITHING=100.0
    FENCING=100.0
    PARRYING=100.0
    SWORDSMANSHIP=100.0
    WRESTLING=100.0
    MACEFIGHTING=100.0
    TACTICS=100.0
ON=@NPCRestock
    ITEM=i_dagger
    COLOR=2
```

**Comment by alexdan2** [comment]
Same happen whit your scirpt, i search deeper if found other usefull information.

**Comment by GitMadKing** [comment]
**also it may be a event or after creation event**
if you change color of weapon in game to the char, after some time it match the weapon color? (maybe on restock or something)?

look at a general event on scripts.
or maybe search inside all script folder
something like "weapon.color" "findlayer.1.color" "findlayer.2.color"

**Comment by alexdan2** [comment]
I also removed all NPC base event called in ini (EventsPet, EventsPlayer, ecc ecc).
Also i check i_dagger and not have nothing, this happen whit all item :(

now i check if happen also on comunity pack script.

**Comment by xwerswoodx** [comment]
This issue occured when the character NPC equals to BRAIN_VENDOR. If it won't be a vendor, use BRAIN_HUMAN.

**Comment by alexdan2** [comment]
I test whit comunity and happen same, this script code:
```
[CHARDEF c_alchemist]
ID=c_man
NAME=#NAMES_HUMANMALE the alchemist
DESIRES=i_gold
AVERSIONS=t_trap
TSPEECH=spk_human_default
TSPEECH=spk_shopkeep
CATEGORY=Civilized
SUBSECTION=Tradesmen
DESCRIPTION=Alchemist (human male)
ON=@Create
   COLOR=colors_skin
   NPC=brain_vendor
   NEED=i_gold
   STR={45 55}
   DEX={45 55}
   INT={45 55}

   ALCHEMY={50.0 75.0}
   EVALUATINGINTEL={20.0 30.0}
   FENCING={20.0 30.0}
   HEALING={20.0 30.0}
   IMBUING={20.0 30.0}
   MAGICRESISTANCE={20.0 30.0}
   POISONING={50.0 75.0}
   TACTICS={20.0 30.0}
   TASTEID={50.0 75.0}
   WRESTLING={20.0 30.0}

ON=@NPCRestock
   ITEM=i_dagger
   COLOR=33
   SELL=VENDOR_S_ALCHEMIST
   BUY=VENDOR_B_ALCHEMIST
```
i test on both version:
10:43:SphereServer Version X1-Nightly [WIN32] by www.spherecommunity.net.
10:43:Compiled at Apr  1 2020 (18:45:18) [build 3254 / GIT hash 1e2d2f5d07e3134b1e676db5fa35017a3eb32e25]

10:40:SphereServer Version X1-Nightly [WIN64] by www.spherecommunity.net.
10:40:Compiled at Apr  1 2020 (18:39:06) [build 3254 / GIT hash 1e2d2f5d07e3134b1e676db5fa35017a3eb32e25]

**Comment by xwerswoodx** [comment]
I already explain that it's because of BRAIN_VENDOR, I will check brains and look if I can find something, but nolok or other developer could fix it as soon as possible.

**Comment by alexdan2** [comment]
Ohh yeah, sorry not readed message (miss refresh page).

Yeah i confirm happen whit BRAIN_VENDOR only.

Thx a lot

**Comment by GitMadKing** [comment]
> I already explain that it's because of BRAIN_VENDOR, I will check brains and look if I can find something, but nolok, xun or other developers could fix it as soon as possible.

why on my side did not happen?
maybe related to some ini flags?

**Comment by xwerswoodx** [comment]
Have you used ITEM under @Create? Because if you use under @Create it works fine, I guess it's because of SELL, BUY restock system.

**Comment by xwerswoodx** [comment]
I already found the issue and fixed it but after I think a little bit why vendors seperated from the other npcs, I remember that the Vendors always restocking their stocks every 10 minutes, so that means it restock the items under @NPCRestock every 10 minutes. So I found out under @NPCRestock section for ITEM colors is totally unnecessary because it filled vendor backpack everytime restock the items. So there is no reason to use ITEM under @NPCRestock for vendors. So in time it will causes a bug (after reached the max item amount in backpack) and also each vendor will have too many unnecessary items in their backpacks. That will cause the lag while saving the world etc. So ITEM under @NPCRestock for Vendors totally unnecessary, you can still use ITEM and ITEMNEWBIE under @Create.

**Comment by GitMadKing** [comment]
the only reason i see to put item under restock
is to permit npc that lost equip to be restored.

Il ven 3 apr 2020, 13:59 xwerswoodx <notifications@github.com> ha scritto:

**Comment by Jhobean** [comment]
Nice point of view xwerswoodx.  So you suggest innactive npc restock on vendor?

**Comment by xwerswoodx** [comment]
There is a NORESTOCK tag which blocks the restock but if you don't want to restock vendor, you can still also use the On=@Create section to give an item to vendor. Because vendors are just for selling items, if they doesn't sell items you can use BRAIN_HUMAN, if you want to sell item but still need a give an item you can use @Create. If you want to create Evil Vendor which you can buy/sell items but it drops items when dead you can use @CreateLoot. So I am not sure why someone need to use @NPCRestock for giving an item? The only reason that I can see, @GitMadKing's reason that maybe someone need to equip item if it's removed, but you can still use memory item or you can still use @Destroy/@ItemDestroy/@Damage/@ItemDamage triggers to block that. If there is really good reason to use ITEM under @NPCRestock, please let me know so we can find a way to do it, or we can create new template.

**Comment by GitMadKing** [comment]
i don't understand why on my side this is not happening

**Comment by alexdan2** [comment]
Tested and work fine, Thx !
