### ISSUE TITLE
Skill Going to negative

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#404]
We have lot of custom item that give a skill bonus. Sometimes, player equip them but don't need the skill so their ARROW pointing down 
![image](https://user-images.githubusercontent.com/51728381/78799278-ea7fa080-7987-11ea-8220-a311bc7fce5a.png)

Since they have a bonus for the item, the skill going down until it reach 0. WHen they unequip the item, BANG!!!!!  skill go negative.
![image](https://user-images.githubusercontent.com/51728381/78799403-126f0400-7988-11ea-880c-4aa4f5f2e1f7.png)

When skill is negative, Sometime, When server resync or save, the skill go back to (100 + negative value) With this example  100+ -20 = 80

It's normal? Core fix possible or I change on script?

I'll post this item for exemple:

```
[ITEMDEF i_pickaxe_sup]
ID=i_pickaxe

ON=@Create
HITPOINTS={31 60}
color=07a1
ON=@equip
src.mining=<src.mining>+200
ON=@unequip
src.mining=<src.mining>+-200
```

**Comment by GitMadKing** [comment]
should not go to negative.
but also using wildly +20 -20 is not a good practice, without an if or some check

**Comment by Jhobean** [comment]
Yes can make a if but will not work for all. The important part is not go negative when it drop of 0.1 when arrow is down.

**Comment by alexdan2** [comment]
I think this is better safe way:
```
[ITEMDEF i_pickaxe_sup]
ID=i_pickaxe
BonusSkill1=Mining
BonusSkill1Amt=20.0

ON=@Create
HITPOINTS={31 60}
color=07a1
```

**Comment by Jhobean** [comment]
Yes for this exemple. Thx for info. Our custom item will not work. Possible to check on skill change if <0. Force to 0

**Comment by GitMadKing** [comment]
if skill < bonus
 skill= 0
endif

**Comment by Jhobean** [comment]
Made an easy fix in the script. Modif in core is useless? Maybe a feature.
```
ON=@Skillchange	//Utilisé pour éviter d'avoir un skill négatif
IF (<ARGN2> > 10000) // Go to negative -1 = 65526
	ARGN2=0
ENDIF
```

**Comment by cbnolok** [comment]
I'll add an additional check and warning in the source, but rather than considering this as a core bug, i see it more as a script error

**Comment by Jhobean** [comment]
Don't seem to work when I unequip a special item

![image](https://user-images.githubusercontent.com/51728381/79051379-f5436b00-7bfd-11ea-8b1a-4e5a8b2865e5.png)

**Comment by xwerswoodx** [comment]
This is not a Sphere issue, if you change skill value with script, you have to check while unequip if he still has enough skill or you have to block skill drop under skill requirement with @SkillChange or @SkillGain triggers. 

Okay I agree when skills goes under 0, it bugged and get higher but, skills shouldn't be less than zero. So I suppose you to make sure noone can drop their skills under items bonus (maybe you can give a tag to save overrided values like TAG0.MINING += 200 and when he try to lower their skill you can block the skill goes under that value. Another fix could be check skillchange if the skill goes under 0 to set 0 and if goes more than skillclass maximum, you can set it skillclass' maximum.

But on the other hand, yeah I agree that 6k bug should be fixed, but as I say this is not a sphere bug totally, most of the bug caused by script's itself.

**Comment by Jhobean** [comment]
Thx I put This in my script:
```
ON=@Skillchange	//Use for avoiding to have negative skill
IF (<ARGN2> > 10000) // Go to negative -1 = 65526
	ARGN2=0
ENDIF
```
