### ISSUE TITLE
Impossible Kill someone with custom dommage

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#406]
We have a little bug with our custom dommage script. Some custom effect apply a DOT ont the char and they lost hit point over time. The problem is if you have 1 hitpoint, and loss 2, your life go to -1 and you do not dye....  After 1 sec, you are a 100% of life.

Here how reproduce it:
```
[FUNCTION test]
hitpoints = <hitpoints> +- <ARGV[0]> 
SAYua 0027 0 0 eng <eval <ARGV[0]>>
```
Juste set the QTE of hit point you need to pass in negative.

Note1: This system was working well on 56d
Note2 : Same on NPC

Note3: If you are GM, dont forget to set .invul to off :-)

**Comment by xwerswoodx** [comment]
Seems like when your hp drops down to negative values, it directly maxed the value, so here is the solution.

```
[FUNCTION test]
LOCAL.HP = <dARGV[0]>
IF (<dLOCAL.HP> > <HITS>)
  LOCAL.HP = <HITS>
ENDIF
HITS -= <dLOCAL.HP>
SAYUA 0027,0,0,eng,<dLOCAL.HP>
```

**Comment by xwerswoodx** [comment]
I checked the code; there is a 2 different version of short values which is **short** and **ushort**. both of 16bits but the difference is short can be set from -32768 to 32767. But on the other hand ushort totally uses positive numbers and can be set from 0 to 65535. This is make the difference. If I change ushort, that lets the hits going to negative and we can check negative values to kill character. But on the other hand, does it really needed? Because normally hits never be less than 0, also the developer who did this change may have his/her own reason or maybe he think same as me, we totally don't need any negative values for stats. So I don't think we need any changes about it, also it lets the others to make npcs with 65535 hitpoints. So It's not totally bug, I suppose you to use that to make sure you have evade that issue;

```
[FUNCTION hpDown]
LOCAL.HP = <EVAL <HITS> - <ARGS>>
HITS = <MAX <dLOCAL.HP>, 0>
```

Or you can use the way I gave you before.

**Comment by cbnolok** [comment]
We need to uniform every signed/unsigned differences in favor of the
unsigned variables, since hits are supposed to be unsigned, this changes
also its maximum possible value

Il ven 24 apr 2020, 11:08 xwerswoodx <notifications@github.com> ha scritto:

**Comment by xwerswoodx** [comment]
I think the way of using ushort is way better than short. Because as I say hits doesn't need to be negative values, so we don't need to half the maximum value for no reason. I don't know who did the changes, generally you did that type of changes, so good work!

**Comment by Jhobean** [comment]
Thx for explanation. All our script is adapted now and its Works well.

**Comment by Jhobean** [comment]
We have same bug it you remove and item with hits bonus.
If you remove the item.

@unequip
Src.Hits -= 10

Yes the script  may be adapte but I think a core fix can be done.

For detection death, check hit <= 0 instead 0
