### ISSUE TITLE
Cast to different floors

### ISSUE THREAD

**Issue by criminalx** [Sphereserver/Source-X#471]
You can cast up and down floor, tried with advanced los and without it. You can see there:
https://puu.sh/FJ0ZJ/0ee981b820.png
https://puu.sh/FJ101/e4e88b9b64.png

https://puu.sh/FJ14k/cc3cf65445.png

https://puu.sh/FJ14y/f398b9d3a4.png

**Comment by canerksk** [comment]
`
// Uses the new LoS algorithm
// ADVANCEDLOS_DISABLED   00 // Disabled, use the old method
// ADVANCEDLOS_PLAYER     01 // Enabled only for players
// ADVANCEDLOS_NPC        02 // Enabled only for NPCs
AdvancedLos=0
`
browse settings in sphere.ini

**Comment by cbnolok** [comment]
Does it work with AdvancedLOS enabled?

**Comment by criminalx** [comment]
> Does it work with AdvancedLOS enabled?

Yes, tested with advancedlos enabled and disabled

**Comment by xwerswoodx** [comment]
Hmm, I made some tests, and see that it's working fine. It's because you find a spot that have a view from stairwell to player, so yes player is lower floor but the place that the attacker is directly see the attacked player from the stairwell. So I don't see any issue here. CanSee meaning Can See, it's direct, so if the players can see other player without anything blocked his vision, he can attack. In this case, the reason is totally same, you have view for other from the stairwell, if you move out of view from stairwell no way to attack.

**Comment by criminalx** [comment]
If you are +Z you cant hit with any spell or bow, only on those ranges

**Comment by Soulless-1** [comment]
@criminalx Can you confirm this issue is still valid? I tested it and it seems to be working properly with/without advanced LOS

**Comment by Soulless-1** [comment]
i tested again, i could not replicate. please comment with some more info and we can revisit this topic
