### ISSUE TITLE
Dismount spell stop

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source-X#527]
When you dismount the magic action stops.  where is the line of code related to this?

**Comment by drk84** [comment]
Seems a big exploit, you can increase Magery with a dismount macro after you cast the spell. Mana will not be consumed, the spell will not create any effect but magery will increase!

**Comment by drk84** [comment]
The exploit works like this:
When then player dismounts while casting a spell the  ACTARG1 value (The spell ID) is overwritten by this line of code in 
the Horse_Unmount method:
` m_atRidden.m_uidFigurine.InitUID();`

Because m_uidFigurine is stored in ACTARG1 this will ovewrite the spell ID and when  we reach the Skill_Magery success stage the spell ID will be considered as -1 and because there is no check for controlling if the spell is valid or not (only a nullptr check)  the spell will succesfully triggers the skill success but this will not cause the spell to have any effect because the new spell ID is -1 (thus consuming no mana and so on).

**Comment by drk84** [comment]
Edit: 
The nullptr check  is enough because a spell with ID -1 is considered null, so it's return 0 inside the nullptr check that causes the problem:

`if (tSpell == nullptr)
			return 0;`

I think we can replace it with -SKTRIG_ABORT

**Comment by drk84** [comment]
Or we should allow to continue casting a spell after dismount?

**Comment by Jhobean** [comment]
What you say drk84 is true and we had big issue like this about the attack!  You attack someone with a bow and at the same time a macro mount Dismount at 0.1 sec.  So you launch an arrow each 0.1 sec!!!!  We added a script function when dismount toggle war mode.

I think your issue is link to that.

**Comment by Jhobean** [comment]
Its possible when unmount it change nothing?  Continue casting?

**Comment by canerksk** [comment]
When you get off the mount, the magic application should continue.  It can be turned off optionally from this script.  this is a usual war dynamic.

**Comment by drk84** [comment]
Should be fixed
