### ISSUE TITLE
CanSeeLos Using Spell

### ISSUE THREAD

**Issue by canerksk** [Sphereserver/Source-X#560]
Hello, when the target is not momentarily in the field of view, the application of magic is successful and the magic word does not write and when we practice the spell over and over again, the last spell is successful.

https://www.youtube.com/watch?v=xK71wABrldU

**Comment by Jhobean** [comment]
Seem to work correct. You dont have the los back to the house but you have it when you see it.    Casting fast like you do make you fizzle the last spell..  i habe difficulty to see where the anomali.

**Comment by canerksk** [comment]
no, it doesn't break the last spell.

**Comment by xwerswoodx** [comment]
I haven't seen any issue, maybe I couldn't catch it because everything is too fast in video, i think you are talking about sometimes spells doesn't fizzled and casted but there is many scripting issues;

Firstly, @SpellSelect trigger is triggering when you select the spell, ARGO is equals the item that used for spell or player's himself. If you want to check before spell cast, you have to use @SpellCast trigger.

Secondly, @SpellEffect already called after target is affected by spell, so that means he is already affected so canseelos is totally useless, So if you want to check canseelos you can use @SpellSuccess trigger which is better solution, but sphere directly cancel the spell if target is out of view, so I don't see the reason that you want to cancel it when it succeeded.

So i think the issue could be script side, but I willing to hear more about issue in future.

**Comment by canerksk** [comment]
No script changes related to spells.  The problem is that when the target player quickly enters and exits the field of view while constantly pressing the spell macro, in some cases the spell is successful even if the target is not in the field of view

**Comment by Jhobean** [comment]
I try to figure what you mean.  
What happen is you have the los when you begin the spell.  When spell was ready to send, you have los too.
After that the player go hide behind house but spell is correctly casted. Where the peoblem?

**Comment by Tolokio** [comment]
> I try to figure what you mean. What happen is you have the los when you begin the spell. When spell was ready to send, you have los too. After that the player go hide behind house but spell is correctly casted. Where the peoblem?

I think the same. This issue could be closed.
