### ISSUE TITLE
wall stone time

### ISSUE THREAD

**Issue by Leodinas** [Sphereserver/Source-X#563]
When I build source x (I didn't change any code)

After casting stone wall magic → archive → close server → open server → 13:56:00 WARNING:FixWeirdness on Item (UID=040001fd6): timer unreasonably long (> 90 days) on a top level object.

The stone wall timer increases automatically.

Does anyone have the same problem as me?

The client is 6.0.6.1

**Comment by xwerswoodx** [comment]
@Jhobean do you still have same issue? Because when I was working with evening, I sent him my build and he tested it is working fine for him, but when we download latest sphere source and build it on his computer, this issue happening.

I thought it was because of visual studio version but he said after he changed the version to 2019 this still occur for him, so maybe it's a toolchain issue? Or maybe something else, I am not sure about it yet

**Comment by Jhobean** [comment]
Seem to be a good theory because that happn to me when i build in local...

**Comment by xwerswoodx** [comment]
Just for information, I am using Visual Studio 16 2019 as generator and do not specify any toolset, can you change your build with this and try it again?

**Comment by Leodinas** [comment]
The problem is caused by GIT
