### ISSUE TITLE
Npcs can pass over multis

### ISSUE THREAD

**Issue by terrikate** [Sphereserver/Source-X#577]
After today's update (3358) the npcs go through multis

**Comment by xwerswoodx** [comment]
It will be fixed in short 👍

**Comment by terrikate** [comment]
@xwerswoodx It keeps happening to me in 3359. Also my character when closing doors of the house and make any action changes height. In case you see a relationship.

If you need more information ask me :)

**Comment by xwerswoodx** [comment]
The closing issue is known issue, that will be fixed by nolok because I have no idea for now what causes it, while system just changed tomorrow so these type of problems can occur. I just made a fix getcanmove check which causes npcs doesn't care walls and move through it. But if it's still happening, I can check it tomorrow, for information, please give any information you have, so that can help us to notice other issues to fix or avoid happening.

If npc problem solved, you can continue #552 while some of known issues given under this topic, so it can be easier for developers to reach it 👍 

If npc problem still occur, if you explain the issue little more we can manage to find out reason

**Comment by cbnolok** [comment]
Yes, NPCs and players somewhat ignore multi components. It doesn't seem related to recent changes.
Can someone track the commit where this started to happen?

**Comment by xwerswoodx** [comment]
After hours of trying, seems like the issue is because of Ultima Online itself. Clean uo build solve the issue at all. If you used legacy mul converter or something like this, I suppose you to remove .mul files to force sphere read uop files instead.

**Comment by terrikate** [comment]
For throwing some light. I use muls in sphere, yes. It happens in all kinds of houses, multis and custom multis. 
I haven't changed anything about it and in version 3354 from December 22nd at 23:12 there is no bug. The only commit after the version that doesn't fail and that touches related things is this https://github.com/Sphereserver/Source-X/commit/f5c2c4bf025e73e184c3330a7bfdc916b8227ea4 but personally I cannot see the problem in the code or something is escaping me

I will keep looking

**Comment by xwerswoodx** [comment]
Uhm, the issue on my side was because of ultima online, yeah it's silly but when I try it with ml and classic versions both working fine for me now. But maybe there is some issue that causes problem for you, Did you used any nudge up, or map point changing script? Maybe it's script side. Because I am working on it for days, also nolok working on it and seems like the issue for me fixed when I clean install Ultima Online, but maybe this can be only my sided issue at all.

On the other hand, I can give you f5c24b build or older than it, and you can check with it if you wish.

**Comment by terrikate** [comment]
I haven't touched anything on a functional level in the scripts. I started working with version X a few days ago and was adapting scripts (I come from a 56b) and as you were getting new versions I was updating until it began to fail. Specifically from December 24th. I can't guarantee that the problem comes from there because I didn't download any version from the 23rd but the one I have from the 22nd doesn't have that problem https://github.com/Sphereserver/Source-X/commit/5b6a91f5d617efa75514819fda8df6e7aaed37ec

![image](https://user-images.githubusercontent.com/13729303/103158383-6000fa80-47bd-11eb-829b-2cad7613da0d.png)

If you want to compile some other version, I'll try it without problems :)

------------------
Edited:

Uhm I just tried today's version (3361) and I don't have this problem anymore. I understand that it was related to #552 then. However, I have hundreds of errors when starting the server of some script that later I will investigate in case it is for something that has been touched recently and I will notify it in another issue

I would say we can close here. Thanks!

**Comment by xwerswoodx** [comment]
Yeah, I talked with @cbnolok a little while ago, he said he found out some issue can cause that, and seems like it fixed your problem, I am happy to hear that.

For closing, you can use Close button, as you are the author of this topic 👍

**Comment by terrikate** [comment]
Perfect! Thanks :)
