### ISSUE TITLE
Bulletin Board "Day" incorrectly displayed

### ISSUE THREAD

**Issue by soulless320** [Sphereserver/Source-X#600]
Bulletin Boards display DAY 0 for all posts (this pic is from sphere) it used to display day 1 or day 2 or day 230, etc
![image](https://user-images.githubusercontent.com/17236327/104248624-dc3f4300-5437-11eb-8704-657e3ee30b71.png)

the below pic is from a different server how it should look.  displaying in serv.rtime  rather than some arbitrary day.
![image](https://user-images.githubusercontent.com/17236327/104249156-d5fd9680-5438-11eb-8fed-05a99d1e518f.png)

**Comment by xwerswoodx** [comment]
I didn't geti on the first pic it shows DAYS 0 and second one gives serv.rtime. How was it working before? I haven't used Bulletin Board for a long time.

**Comment by soulless320** [comment]
Before it would show DAY0, DAY1, DAY2, DAY3, etc. i noticed it was broken, but honestly it's been wrong for a long time. I only thought to do something about it while making this Renaissance era shard, when making the bounty and kidnapping boards. 

reading "day #" doesnt mean anything to the person reading it, how do they know what day they are on?  having a month + day will let them know when the post was truly made

**Comment by Ben1028** [comment]
Changing it to a date format is a simple fix (done already) but the issue comes with backward compatibility, as the messages are saved using a server timestamp, not real world timestamp, so it displays a date from way back in the past.
Only way here would be to change the timestamp, but old messages would have wrong date.
