### ISSUE TITLE
Overweight / Item Drop

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#633]
You should be allowed to be overweight by 120% (this should be an INI setting IMO) of your max weight before items cannot be added to your bag. I think this would correct lots of issues with "overweight items dropping to ground" that some of my players have mentioned. example: having a full bag up to almost your total weight, then filling it with folded cloth the rest of the way, if you cut the cloth, the bandages will drop to the ground. 

when you are overweight you should get this message 
![image](https://user-images.githubusercontent.com/17236327/107463555-58f33900-6b2c-11eb-9e58-c9223c1a2485.png)

when you are beyond 120% of max weight you the item should be bounced back to where it was and you receive this message
![image](https://user-images.githubusercontent.com/17236327/107463577-67d9eb80-6b2c-11eb-88e9-6196e2ecfe90.png)

should be an INI toggle though for players to customize it

**Comment by Tolokio** [comment]
Bandages gained from cloth have more weight than the cloth? or bandages are bounced before  removing the cloth?

**Comment by soulless320** [comment]
same weight, and item's are removed before new items are added. 

our weight system in general doesnt work quite right.

**Comment by soulless320** [comment]
I have some observations about weight 

after doing some tests on live UO, and confirming on some era shards for the era im replicating (uosecondage, uorenaissance), weight should work differently on sphere, to be consistent with UO.

You should not be unable to put an item in your pack if you are overweight, you are just overweight and take a stamina penalty. whatever the container max is for items, thats the point at which you should stop being able to put things into your pack.
for the backpack on my chars I had  475/390 weight and the backpack was 400ish stones. I got the message "That container cannot hold more weight." not just because i was overweight, but because the containers were overloaded.

as far as the stamina went:

it seems like being 15 stones over your max limit you lose 1 stamina per step. (405/390 lose 1 stam per step (103.85%))
roughly about 30 stones over your max weight you lose 2 stam per every step.  (419/390 lose 2 stam per step (107.44%) (2 stamina is the max you lose per step) )

in the past there has been tricks where plays will weaken another player, and eventually they will not be able to hold their items.  This was fixed I believe, but I think this alternate weight system will be more accurate, and a better fix for that.

people will not run around with backpacks loaded to 400 stones, because they will not be able to run with them. they will carry their proper weight at which they do not get a stamina drain penalty. This will leave a decent buffer area for things like weaken to not affect the players item capacity, only their stamina drain. 

Hopefully that makes sense to everyone.

**Comment by Jhobean** [comment]
Coruja made some modif on 56d about these feature. He inplemented a bug where you can take an chest with 1000000 stone and walk all britain. You have illimited power when lifting something and do not lost stam when walking. It was the last modif I saw on 56d befire going to x

**Comment by Soulless-1** [comment]
the following settings in ini should make it so someone can achieve a properly working stamina loss / weight system for a standard UO server.

how many steps to lose stamina on walking
how many steps to lose stamina while running
how many steps to lose stamina while walking with mount
how many steps to lose stamina while running with mount
what % overweight do you lose 1 stamina per % over weight (5=every 5% overweight lose 1 stamina per step)
what weight you can achieve over your carry weight, -1 = backpack maxweight

**Comment by Soulless-1** [comment]
Any thoughts on adding something like this? I think it would be beneficial. I know right now I cant make a proper UO weight system without allowing items over the maxweight

OverweightStaminaLoss=30                           //steps you can take while moving before losing 1 stamina
OverweightStaminaLossMounted=60             //steps you can take while moving on a mount before losing 1 stamina
OverweightStaminaLossModifier=5                //every % overweight of this, you lose 1 more stamina
OverweightMaxCarry=-1                                 //what amount of weight you can carry over your max, -1 = container maxweight

**Comment by Soulless-1** [comment]
Im going to combine this request into a new one, there are several factors in weight / max carry / dragging that need to be looked into.
