### ISSUE TITLE
Item timer do not set if value is on @create

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#662]
Edit: whem create an item, if timer value is on the @create, timer is not set and stay at -1

[ITEMDEF i_mem_symbol] 
ID=i_memory 
TYPE=t_eq_script 
NAME=Cool down Symbol Pretre 
on=@create
timer=4
ON=@TIMER 
REMOVE 
RETURN 1  

https://github.com/Sphereserver/Source-X/commit/3dbb44713bec5d720cf3b932970584331637ec18

**Comment by alexdan2** [comment]
Confirm

**Comment by xMirroRx** [comment]
As Alexda said, there is no problem, it works fine.
[function f_Test1]
serv.newitem = i_test1,1,<src>
new.timer = 2

[itemdef i_test1]
id = i_memory
type = t_eq_script

on=@timer
serv.log ## @Timer
remove
return 1

on=@Destroy
serv.log ## @Destroy

17:53:(_ggg,22)## @Timer
17:53:(_ggg.scp,27)## @Destroy

But there is another problem try this. The item will not be deleted since it will remain stuck at Timer = 0.
@Timer not firing

[function f_Test]
serv.newitem = i_test,1,<src.findlayer.21>
new.timer = 2

[itemdef i_test]
id = i_box_wood
type = t_normal

on=@Timer
remove
return 1

**Comment by alexdan2** [comment]
@xMirroRx 
I never used your sintax but is possible because try to place in backpack a memory have to placed in different layer.

serv.newitem = i_test,1,<src.findlayer.21>
<src.findlayer.21> is the container of item right ?

**Comment by alexdan2** [comment]
Yes i make better test and confirm @xMirroRx  issue, timer keep on 0

**Comment by Jhobean** [comment]
Ok Here how reporduce my issue:

When casting .test, item appear on the .edit direct with timer = -1
```
[FUNCTION test]
SERV.NEWITEM=i_mem_symbol
SRC.EQUIP = <NEW.UID>

[ITEMDEF i_mem_symbol] 
ID=i_memory 
TYPE=t_eq_script 
NAME=Cool down Symbol Pretre 
on=@create
timer=400
ON=@TIMER 
REMOVE 
RETURN 1
```

**Comment by alexdan2** [comment]
@Jhobean 
 I think can change title in multiple timer issue, because issue tell @xMirroRx not connected by create, simple item in container when set a time stuck to 0.

**Comment by Jhobean** [comment]
Seem. To be 2 differents bug.
- set on @create
- timer trig on container

**Comment by alexdan2** [comment]
> Seem. To be 2 differents bug.
> 
> * set on @create
> * timer trig on container

Yep is two different situation.

**Comment by slow-loki** [comment]
![timerbug](https://user-images.githubusercontent.com/73989785/117410726-b53ade80-af0a-11eb-8cf9-ffddb8c2f44f.gif)
As request by Jhobean to upload an example.

**Comment by cbnolok** [comment]
Sphere was never able to have active timers on items inside containers. That was done for performance reasons, due to how timers were handled in the past. For this reason, that single issue isn't to be considered a bug.
That said, sphere x handles timers differently and can very much afford timers for items inside containers. It can be discussed if we now want to allow those or not, but on a separate issue.

**Comment by soulless320** [comment]
appears to be fixed, thank you Nolok
