### ISSUE TITLE
Mount/Pet

### ISSUE THREAD

**Issue by youhide** [Sphereserver/Source-X#681]
weird behavior is occurring when your pet/mount start fight and don't kill the target... he stay stuck and dont answer command follow anymore...
bonded pet start following the opponent after die and never follow u anymore...
animal sound loop persist when this happen.

**Comment by drk84** [comment]
I did some tests, the pet seems to stay stuck only when you give the follow command while the pet is in combat. 
Afterwards, the animal sounds loop happens when you use the .remove command on the attacking creature
Also how can the pet follows the opponent if he is dead? If you mean a player opponent then specify it

**Comment by drk84** [comment]
fix sent

**Comment by youhide** [comment]
thanks!
