### ISSUE TITLE
MAGICF_NOCASTFROZENHANDS with spellbook\wand

### ISSUE THREAD

**Issue by GitMadKing** [Sphereserver/Source-X#692]
Disabling this option in sphereini still not permit casting if had spellbook or wand in hand.

i think that should be excluded or added an option for them, because doing it by script seems preety hard to overwrite all paralyze spell

**Comment by drk84** [comment]
Fix Sent

**Comment by Soulless-1** [comment]
Can confirm it is fixed, but the message is a bit confusing "you can't reach anything in your current state"
I think the message when blocked from casting due to items in your hands should be similar to other ones dealing with hands. stealing for example : "You must have both hands free to attempt stealing."

and it looks like it doesnt check layer 15, which is light items.

**Comment by drk84** [comment]
Layer 15 is layer_face since some years, it's used by the enhanced client.

**Comment by Soulless-1** [comment]
oh, interesting I have it as the light layer. i used it to stop npcs from moon walking on 7.0.20

**Comment by drk84** [comment]
I close this
