### ISSUE TITLE
Mounts disappear with DISMOUNT command.

### ISSUE THREAD

**Issue by LuxionUO** [Sphereserver/Source-X#728]
It doesn't happen every time, but sometimes when you do the **SRC.DISMOUNT** the mount just disappear (like .remove) but the owner still sees the mount in the follower list, I think it means that doesn't call the **@FollowerUpdate** trigger at all. If you have a custom Pet System like me it makes it very hard to restore the mount.

**Comment by Soulless-1** [comment]
can confirm, just tested this and dismount made my horse disappear about 1 seconds after I used .dismount

**Comment by alexdan2** [comment]
Me also i confirm, this issuee is very old, is arount 1 yeah i see it.. 

Not sure if connected only whit shrink pet or is general one.

**Comment by Jhobean** [comment]
On my side I cant reproduce....
```
[plevel 1]
test

[FUNCTION test]
src.dismount
```

**Comment by LuxionUO** [comment]
@cbnolok could you give me an update on this? It's really a problem when you have a customized experience system for Pets and after 1 month of farming the Pet just magically disappear. Players are getting upset about this.

**Comment by cbnolok** [comment]
Sadly i don't see me having time or energies for sphere in the near future, i read that perhaps someone fixed this for the time being via script? 

Il giorno 21 gen 2022, 21:47, alle ore 21:47, Luxion ***@***.***> ha scritto:
***@***.*** could you give me an update on this? It's really a problem

**Comment by LuxionUO** [comment]
Oh, sorry to hear that, I don't know if someone fixed via script but if someone did would be lovely, do you have any idea about who can be? Thanks for your answer and collaboration anyway ;) @cbnolok

**Comment by Jhobean** [comment]
With help of @JulianUO , I achieve to make a partial "reprduction".

When you ride a mount, the real NPC stay there and is hidden next to you. If this NPC Die, you can continu to mount but at the moment you unmount you see your horse die. It's what happen to you @LuxionUO ?

If you want to test, you can see your hidden npc by activating .allshow + .debug ( only after this pull request is merge https://github.com/Sphereserver/Source-X/pull/829 )

https://user-images.githubusercontent.com/51728381/150624295-c7af2d91-eb36-49ba-b3fc-13c6eab90bd9.mp4

**Comment by Jhobean** [comment]
Posting here some teport on discord
`Hi, a bug is happening with me when the char is mounted (tested with llama and horses) and the shard saves when you are on the same tile of a field spell (Paralyze, Fire or Poison) that you cast. When you restart sphere, the mount dies and the body is changed to a random human.

Steps to trigger this bug:
1st: Cast a field type spell (Paralyze, Fire or Poison)
2nd: Step on the field with the same char that you cast the field.
3rd: Save the shard (The following message appears “mount_name_here appears to have decided that it is better off without a master!” and in the sphere console an error will appear “code=0x1103 (Ridden NPC not acting as such)".
4th: Close/Restart Sphere.
5th: When you enter your shard and tries do double click your char to dismount, the mount dies.
Tested with Sphere X - Aug 20 2022 11:52 am (But this is happening with old builds too).`

**Comment by Tolokio** [comment]
So, does it only happens when animal is dead, or happens if he is alive ?
I can't reproduce it.

**Comment by Jhobean** [comment]
Set a z Lower will probably prevent futur damage.

What aboit the poison or tick damage comming to the pet after you ride it.  Pet should become invul? If no,.we could make a check when NPC die if isridden, unmount and print a message npc is death.

**Comment by Soulless-1** [comment]
looking back. It wasn't based on damage when I replicated this. It just doesn't always happen. I did not damage the mount at all when I confirmed this happened.

I dont think changing the Z level for an offline mount to keep it from getting damaged by AOE spells is the right solution here. That also would be one that is not quite complete in it's solution, since someone on a mountain top could potentially be at the highest possible z level.

**Comment by Jhobean** [comment]
I think a simply "patch" could be to peint a message to horse owner his  pet is death and force an unmount... Right now, npc die and you know it 1 hour later when you unmonth

**Comment by Tolokio** [comment]
I got a fix for this at my pull request. Not tested.

**Comment by Soulless-1** [comment]
you probably should test those first

**Comment by Tolokio** [comment]
It will test, it is not real pull request is just to talk about the code. I prefer not to lost fime coding something that will never be accepted cos dosnt get into sphere's standards.

The z-127 fix is to avoid damage taken by t_fire or firefields. I Think as u, it dosnt look as the problem of the issue. Did not test but I someone told it were happening.

The last fix I added is to unmount char if mount dies and is being ridden.

Luxos or anyone able to reproduce, should add this event to mounts to see if it is caused by the mounts being dead or mounts can be damaged by.

On=@gethit
if (<flags>&staft_ridden)
serv.log takes damage while ridden Hits-> <hits> / <maxhits> Damage-><argn1>
endif

on=@death
if (<flags>&staft_ridden)
serv.log animal dead while ridden.
endif

**Comment by Soulless-1** [comment]
I was able to replicate the results, but not consistently. 
You dismount using .dismount, the mount disappears 1 seconds later.
no trace of the mount when it happens

**Comment by Tolokio** [comment]
I tried to reproduce this many times. I can't unless mount is dead

**Comment by Jhobean** [comment]
With @Tolokio PR https://github.com/Sphereserver/Source-X/pull/931
When your pet die you will know it.
I'm pretty certain this issue is link to a death horse but you know it only when you unmount. Now, youbwill unmount automatic and you will be able to modify @death trigger if you want.

Since we dont have more way to reproduce your bug, we should close this issue.

**Comment by Tolokio** [comment]
The message "mounts appear to have decided..." could be provoked because when u attack a pet it decides is better without you. But that can't happen anymore while it is being ridden. Ill try to test asap.

**Comment by Tolokio** [comment]
Could we close this?

**Comment by Soulless-1** [comment]
I havent been able to recreate reliably. ill try again. 

@drk84 may i have access to close out issues, for times when they are abandoned? ill go through my open ones this evening also ;)

**Comment by LuxionUO** [comment]
I didn't experience this issue again honestly, if it will happen again I will reopen the ticket.

**Comment by Tolokio** [comment]
Re-open this issue plz

Somehow mounts can change their action. Probably by script. If action changes, garbage collection will remove the mount for X reason...

Possible way to reproduce the bug: Just change action to a mount when it is ridden. Then do garbage collection, or save, or reset server (I did not test it)

**Comment by cbnolok** [comment]
You can try to add a serv log in the source when the action is changed from npcact_ridden, it might point to the script line involved

**Comment by xwerswoodx** [comment]
I just wonder how ridden horse change it's action, because there should be no way, even I am always mounting a horse all the time and it never changed it's action for me, but if there is a bug we should check it.

If you change it's action from script, this is totally script-side bug, honestly I totally disagree to add limits because other people can like to do other things with changing that actions, also you have never remove STATF_RIDDEN flag from ridden horse for any reason, STATF_RIDDEN means it's used by someone else so if you remove that flag by script, that makes Sphere count that npc is not ridden and remove it's linked objects from world. 

But if the action changed by the server, we need more information about that for fixing it, because this never happened to me honestly so I have no idea how to reproduce it.

**Comment by Raylde** [comment]
Sphere right now delete the mount if dont have the follower requirements:
- If have the Statf_ridden, the Action need to be NPCACT_RIDDEN
- Require a link mount item (t_figurine or t_eq_horse) 

So please, need re-evaluation or we process to close the issue

**Comment by Tolokio** [comment]
Hi there. Sorry. I have no time for sphere and Im not checking emails, gits or discord.

This bug never happened to me and im not able to reproduce it. Until I know, someone reported that rarely some mounts still being removed in his living shard. I dont remember well, but he gave me info that allowed me to track his issue to one of the FixWeirdness() functions. So somehow skill still being changed.

As I said when I did the fix for the mounts system this system can be improved, have been untouched for many years until I did. And my programming skill are very bad for it.


> honestly I totally disagree to add limits because other people can like to do other things with changing that actions

I totally agree with this. And told about this before. We should rework the system to let people use ACTION on mounted chars. In my case I would like to use this feature so I dont need to fake actions of ridden mounts during combats and let the mounts do the action itself. 

Right now, the "mount status" is stored as: statflag->statf_ridden and by action->npc_act_ridden (or something like this)
There is no real need to have 2 places to store this info. For me it is duplicated information. I think I understand it is done like this for minimal optimization at certain point the of the code, but it dosnt worth to have two places with the same info for that minimal optimization. We should remove one of them and I propose we should free "action" to let players use it. 


@cbnolok 
> You can try to add a serv log in the source when the action is changed from npcact_ridden, it might point to the script line involved
-As im not able to reproduce the issue, it would not help. But we could add a check to main to avoid the mount to be removed when it loses the action but it is being used by a char, and as u say add log always this happens. So this way Fixweridness() will fix automaticaly the problem instead just removing the problem.
