### ISSUE TITLE
monsters cannot cross into town, no toggle to control behavior

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#735]
There needs to be a toggle to control this behavior, it's not the standard UO behavior. Monsters are able to cross into guarded town always. They can spawn inside guarded towns as well, this has never been a standard UO behavior in the past. 

One reason also that this is a bad idea to prevent evil npcs from going into town is that it can be abused. you could drag a tamable monster back with you to town limits, and try to tame it, you then would be able to tame this creature which would usually be hard, without any kind of risk of concern of being hurt. 

I think also this toggle (OF_GuardOutsideGuardedArea) in the INI should allow people to have guards actually spawn in outside of town limits as well, there are instances on OSI such as in jails and in guard towers, where the region is not guarded, but guards will be inside of it.

**Comment by criminalx** [comment]
It happen from old times,  like tameables or any npc, you bring it to guards line and keep shooting with bow

**Comment by cbnolok** [comment]
We could add another ini property like NPCBehavior (suggestions on the name accepted), having:
// 0001 // NPCB_GuardWalkOutsideGuardedArea (moved and renamed from OF_GuardOutsideGuardedArea)
// 0002 // NPCB_Guard(Exist/Spawn)OutsideGuardedArea
// 0004 // NPCB_GuardTolerateEvilPets
// Free slots for any guards ideas
// 0020 // NPCB_EvilSpawnInGuardedArea

I would be happy to accept pull requests here, if someone likes this idea, otherwise i feel this as a low priority and devs should work on this on X2.

Btw, i don't think you should always allow evil npcs into a guarded area, just to avoid that taming exploit. Though, i don't have in my mind any great solution.

**Comment by Soulless-1** [comment]
in UO in general there has never been a rule to prevent evil npcs from entering town, its frequent that they will follow you across the boarder of the guarded town, I can only see issues and no benefit from stopping them entering guarded areas. the taming exploit was just an example, im certain barding can be exploited, magic resist, etc.  Especially since thats the purpose of guards, to protect the town so imo its not something that needed to be added anyways. I think we should leave custom behavior to the admins to decide on.  I'll send a pull request just as soon as I figure out for what is causing mine to not go through. I Fixed several issues on my own shard such as guards not walking in non guarded areas, and not spawning in them, evil npcs not crossing into guarded areas, etc.

**Comment by Soulless-1** [comment]
This was resolved 
https://github.com/Sphereserver/Source-X/commit/eb5f876d931b9ba3a3893b572360b07d64de7608
