### ISSUE TITLE
ON=@UserchatButton Do not work like expected

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#783]
@UserchatButton should trig when someone pres chat button
![image](https://user-images.githubusercontent.com/51728381/136862136-36eb15f7-4dce-4686-8a3b-fb1499002971.png)

First bug: On X and 56d, it do not work. Seem to be related to client version

Second bug: @UserchatButton trig at every login

**Comment by Jhobean** [comment]
Just let this here but it may be link to the packet 0xB9 (not existing on sphere)
http://uo.torfo.org/packetguide/

![image](https://user-images.githubusercontent.com/51728381/137014277-be994dcf-27c0-499f-885a-71daa160245d.png)

**Comment by xwerswoodx** [comment]
The problem is there is no Packet for User Chat Button anymore, it replaced for a while and now clicking UserChatButton is totally useless and probably causes some collision because there was a packet that sent when you click chat button. But now that packet send by client at the beginning as clear so it triggers the @UserChatButton.

Because of there is no packet that can be used for this anymore, I probably gonna remove that trigger, and add new triggers like @UserChatJoin, @UserChatCreate, @UserChatLeave which can be trigger when you click Create, Join and Leave buttons, I can't accept that as a bug as this is totally changed client-side we have no way to fix it.

**Comment by Jhobean** [comment]
On osi chat button do not work anymore? That make non sense

**Comment by xwerswoodx** [comment]
Because it works directly on client-side it doesn't send any packet anymore, It's silly but in reality there is no packet we can track that player click the button. When you click create, join and leave it sends packets to server but char button open the menu directly client-side.
