### ISSUE TITLE
Bit mask does not work with more1 on big numbers anymore

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#784]
On 56b the following code would work fine:
```
if <findid.i_ability_item>
  findid.i_ability_item.more1 = <findid.i_ability_item.more1> | 080000000
  serv.log 'DEBUG' more1 = <findid.i_ability_item.more1>, hval = <hval <findid.i_ability_item.more> | 080000000>
endif
```

On SphereX `080000000` is silently not added to more1 and this test code gives the following output (I would expect to see `more1 = 080000000`):
```
02:33:(static_quests.scp,8342)'DEBUG' more1 = 00, hval = 080000000
```
Seems like SphereX cannot handle this operation due to `080000000` is bigger than max 32-bit int value. 

However checked the same scripts with 56c/56d binary, and it works fine there, as you can see below more1 was assigned `080000000` successfully. 
```
02:29:(static_quests.scp,8342)'DEBUG' more1 = 080000000, hval = 0ffffffff80000000
```

**Comment by a1exp** [comment]
I was looking at SpehreX source code and noticed that writing more1 has some logic around it and depends on item type.

In my example above i_ability_item has type t_eq_script. I did another experiement, if I change item's type to t_spellbook than more1 is written fine with `more1 = 080000000`. 

Is it possible that the issue is somehow related to this piece of code or similar logic around more1? 
https://github.com/Sphereserver/Source-X/blob/96ad8d189dc07e5f9f9bcc3cf6e91cdd165506e7/src/game/items/CItem.cpp#L2208

**Comment by a1exp** [comment]
Seems like coincedence of magic numbers :) 
`#define UID_F_RESOURCE		0x80000000`
https://github.com/Sphereserver/Source-X/blob/6e5630ba23ed67f1ae2e80728ebf5f8def9a0ced/src/common/CUID.h#L18

So sphere belives mask 080000000 stored in more1 / more2 is a resource. Perhaps this check should have been added to  specific types like `IT_SPAWN_CHAR` and similar, not to default case? 

@cbnolok could you comment on this one?

**Comment by xwerswoodx** [comment]
> @Jhobean did a little research on this and said `m_more1` is dword on SphereX.
> 
> That's even more weird then. Since 080000000 = 2 147 483 648, and dword can store up to 4 294 967 295.

it depends on the variable is unsorted or not, uint can store up to 4,294,967,295 but it only stores positive numbers. but int can store between -2,147,483,649 to 2,147,483,648 which equals to 4,294... in total. so more1 can keep the both negative and positive numbers if I remind correctly, so it can be int not uint. But you can still keep 64bit values on tags instead of more1/2

**Comment by a1exp** [comment]
@xwerswoodx I suppose by "unsorted" you mean unsigned. Well, AFAIK dword = unsigned int32. 

[For reference](https://github.com/Sphereserver/Source-X/blob/62167fc27529c7ea548b4b6ca61cbba2944534cf/src/common/datatypes.h#L60)

Tags can be used indeed, this is rather a question of backward compatibility with 56b scripts, as such kind of issues is hard to catch.

**Comment by xwerswoodx** [comment]
sorry yeah I meant unsigned, I don't know why I wrote as unsorted anyway :) Yes I remind that nolok did a change about it because before spellbooks not working fine because of more1 and more2. Is it still an issue? Because it should already been fixed. But if it's still has an issue, we can take a look for it.

**Comment by xwerswoodx** [comment]
Anyway I found out the reason, as I couldn't explained before, It's same what I was thinking, because of https://github.com/Sphereserver/Source-X/blob/62167fc27529c7ea548b4b6ca61cbba2944534cf/src/game/CWorldImport.cpp#L474C5-L474C44 called with atoi over here, it ready more values as int, not uint or dword.

I will gonna pr for it, you can test if works if you wish.

**Comment by xwerswoodx** [comment]
I think it's already fixed, but you can re-open issue if you still have any issue.
