### ISSUE TITLE
Is there a way to add spell cast flood protection back?

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#787]
In Sphere 56b when you press and hold a client macro like (cast spell hea, target self) number of lines for spell cast is limited to 3. 

In SphreX (actually started with Sphere 56c) you will see spam. Players are complaining thata "casts are flying away up" :). You will not notice such thing on Orion, only on default client (I used 5.0.6 and 2.0.3 for tests).  

This might seems like a client issue, but Sphere 56b somehow protected from it. You can see videos below.

56b:
https://user-images.githubusercontent.com/31130012/138567443-475c462b-776e-4673-8ce0-c8591100f5fd.mp4

SphereX:
https://user-images.githubusercontent.com/31130012/138567454-398a3705-1a15-4556-9be6-19737deb7e03.mp4

![image](https://user-images.githubusercontent.com/31130012/138567506-0409735c-d262-4445-990c-39d0b4c000a5.png)

**Comment by Jhobean** [comment]
This do not happen on orion client. The "fix" I reverted last week caused this

**Comment by Leodinas** [comment]
Speak((pSpellDef->m_sRunes.GetBuffer()) + 1, (HUE_TYPE)WOPColor, TALKMODE_SPELL, (FONT_TYPE)WOPFont);
change
Speak((pSpellDef->m_sRunes.GetBuffer()) + 1, (HUE_TYPE)WOPColor, TALKMODE_SAY, (FONT_TYPE)WOPFont);

**Comment by Jhobean** [comment]
@Leodinas yes its the old fix. But it cause other issue that he reported.

**Comment by xwerswoodx** [comment]
Best way we could do it, we can add flag for it, so you can choose to use TALKMODE_SAY or TALKMODE_SPELL, because we could add flood protection in sphere-side but what we can do best is just blocking if already has 3 lines in your screen, but that can cause so many issues, for example, if you used nightsight spell and use paralyze spell on someone, if we add block players couldn't see An Ex Por lines but still get paralyzed. This issue is totally client-side. If you are using any custom client, you could add protection or you can request owner to add protection in their clients. I can check color codes, and see if I can do anything to still send packet as a TALKMODE_SAY but ignore the color codes and use wopcolor that defined in messages.scp.

**Comment by Jhobean** [comment]
I think bug occur only on official OSI client.
Orion have an embeded fix for that.

**Comment by Jhobean** [comment]
#1325 PR will help for people using OSI
