### ISSUE TITLE
CONTROL randomly crash client

### ISSUE THREAD

**Issue by Tolokio** [Sphereserver/Source-X#888]
![image](https://user-images.githubusercontent.com/20745578/185804394-74e51386-9294-4741-9538-1e5ca0adffbf.png)

I thought it was my modification, but not, sometimes, when I do .control on a c_headless, client crash but not sphere. It looks random, dosnt happen again for a while once u reconnect.

**Comment by cbnolok** [comment]
Original client or 3rd party? Which version?

**Comment by xwerswoodx** [comment]
I have tried it, by hand, even I created a macro that says .control than target self, and hold the button for 1 minute, but it never crashed. It may be because of Chat system, as it had some bugs that gives debug, but it maybe fixed in my pr I am not sure, but it doesn't happen to me, I can't reproduce.

**Comment by Soulless-1** [comment]
I cant replicate that issue, can you please confirm @Tolokio  if you are able to still cause the issue?

**Comment by Soulless-1** [comment]
closing out, please comment here if you can confirm the issue
