### ISSUE TITLE
Impossible to drag and drop equip item on other player.

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Source-X#901]
Normally when you are GM, you are able to drag and drop some cloth on other player or NPC and equip them on them.

On x version it's impossible. You can remove them but not equip.

**Comment by drk84** [comment]
As GM i can equip / unequip NPCs but not players

**Comment by Jhobean** [comment]
@drk84 on my side it do not work for player and not work for Npc.  On 55i/56d it work.

**Comment by Soulless-1** [comment]
same, cannot do it for npcs or players

**Comment by xwerswoodx** [comment]
I am trying that with a player char,

- I spawned an alchemist
- Transfer it from Gm char to Player char
- Trying to undress with player char
- Successful
- Tried to dress up again his own robe
- Successful
- Tried to dress up with player's robe
- Successful

The only item that I couldn't get from backpack is lantern (because it's newbiefied), except it I could take everything and put everything on him.

**Comment by Soulless-1** [comment]
Actually i just tested and it seems to be working fine, as you say. Though i recall in the past i could not do this. I can confirm on the latest build this works without issue.

**Comment by Jhobean** [comment]
I dont know if I expressed correctly but I mean item on the paperdoll. It do not work at all.

Only way to remove an item on someone is do .xbounce and choose the item.

**Comment by xwerswoodx** [comment]
I sent a video, did you check it @Jhobean I am taking and putting on paperdoll at video, maybe I misunderstanding you

**Comment by Jhobean** [comment]
Effectively. Working noce on NPC.
About player dont seem to work.

Need to work with online player and  non online (.allshow)

**Comment by Jhobean** [comment]
Easy way to test is doing a .dupe on you.

Freeze your new you and try to equip/unequip paperdoll

**Comment by Jhobean** [comment]
Fix thx
