### ISSUE TITLE
Negative stat modifier applied on stat with lowest value, returns maximum value.

### ISSUE THREAD

**Issue by kikeking1** [Sphereserver/Source-X#963]
When I apply a negative modifier to a stat and it exceeds the amount of the stat, instead of being 0, it deducts from 65535, causing the stat to increase.

Eg A character with 10 dex suffers a -20 penalty to his moddex and his dexter becomes 65526.

The stat modifier should be able to be negative (for example -80), but if the stat is 20, it shouldn't go above 0.

![imagen](https://user-images.githubusercontent.com/4921179/200124857-883c78e9-4627-42e5-b72c-292b750608ea.png)

**Comment by Jhobean** [comment]
Similar fix with stam/hits/mana
https://github.com/Sphereserver/Source-X/pull/625

**Comment by drk84** [comment]
It's not a similar fix, the difference is that modstats can go below 0 while the related stats no.

This bring the following issue:

ON=@Equip
src.modstr -50
ON=@Unequip
src.modtr 50

Currently a character with 40 str equipping this item will go below 0 and thus it will get a 65k value of str.

If we internally add a check that avoid a mod value to bring the main stat below 0, the player Unequipping the item will get a 50 str value instead of his original 40 value.

That's because, unlike spells stat modifier, modStats modifier are not tracked anywhere. 

So the best solution for me is that the scripter is responsible to check if a modStat will bring the stat below 0. (It's a simple script)
```
Example:
//Argn1: ModStr value
[FUNCTION setModStr]
if (<tag0.override.modstr>)
	modstr -= <tag0.override.modstr>
	tag.override.modstr = 
	return 
endif
if ((<str> + <argn1>) < 0)
	argn1 = -<str>
	tag.override.modstr += <argn1>
	sysmessage @50 Modstr overrided to <argn1>  
endif
modstr <argn1>
```

**Comment by Jhobean** [comment]
Seem legit to me. Tag.override.modstr wiil be a custom modstr only in script side?

**Comment by drk84** [comment]
yes

**Comment by Tolokio** [comment]
```
on=@statchange
if <argn1> <= 2 //if str dex or int
    if <argn3> <= 0 //if new value will be negative or 0
        argn3=1 
    endif
endif
```
I think this or something like this is the best way to fix it.
str is <modstr> + <oSTR> so no more would be needed.

**Comment by cbnolok** [comment]
That should be double checked, then if there's still overflow, the wisest thing would be only to limit the stat to 0 before overflowing

**Comment by Tolokio** [comment]
Im working on this. There are few ways to follow.

1-Let stats be negative, or at least reach @statchange being negative.
        Maybeit could be interesting to let hits or mana be negative, but stats and maxstats... no real sense.

2-Do nothing. not the best but at @statchange u can get negative value back. I explain:
       Ushort transform negative value into positive value but keep original value. so -5 in ushort will be (65535 - (5 -1)) = 65531
       This way u can recover the negative value at @statchange-> argn3 and use it to create ur own formula.
       
3-Set value to 0 if it is negative before it becomes ushort. 
     This would be the easies way, but you lose information.
     
     
In my opinion, best way would be a total rework, but third way is einfach and solve the problem.

**Comment by cbnolok** [comment]
Addressed with a recent commit.
